// <auto-generated />
namespace GaragePlanches.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addValidationDateWO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addValidationDateWO));
        
        string IMigrationMetadata.Id
        {
            get { return "201604051159038_addValidationDateWO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
